### ISSUE TITLE
Annotate uniqueness contraints

### ISSUE THREAD

**Issue by fdietze** [renesca/renesca-magic#6]
and generate code to create the constraints

**Comment by cornerman** [comment]
could be combined with the matches factory function

for example, having a UuidNode:

``` scala
@Node trait UuidNode {
    @unique val uuid: String = ...
}
```

this should produce a UuidNodeFactory function: 

``` scala
def matchesOnUuid(uuid: String) = this.matches(uuid = Some(uuid), matches = Set("uuid"))
```
